/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.CitasDAO;
import Controlador.DoctorDAO;
import Controlador.ForGraphics;
import Controlador.HabitacionDAO;
import Controlador.PacienteDAO;
import Modelo.Paciente;
import java.awt.*;
import Modelo.Citas;
import Modelo.Doctor;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Abraham
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        setResizable(false);
        //setIconImage(Toolkit.getDefaultToolkit().getImage(Main.class.getResource("/Images/iconmain.png")));
        initComponents();
        DefaultPieDataset data = new DefaultPieDataset();
ForGraphics fg=new ForGraphics();
        data.setValue("Internado", fg.Cuenta("select count(idPaciente) from paciente where Estado = 'Internado';"));
        data.setValue("De Alta", fg.Cuenta("select count(idPaciente) from paciente where Estado = 'De Alta';"));
        data.setValue("Citado", fg.Cuenta("select count(idPaciente) from paciente where Estado= 'Citado';"));

 JFreeChart chart = ChartFactory.createPieChart(
         "Pacientes Registrados", 
         data, true, true, false);
        // Crear el Panel del Grafico con ChartPanel
        ChartPanel chartPanel = new ChartPanel(chart);
        jPanel8.add(chartPanel);
    }
    public void actualizarTabla(String sql, javax.swing.JTable tab){

        //final String tab = "Proveedor";//esto pede ser parametro

        String driver = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/hospital?useTimezone=true&serverTimezone=UTC";
        String user = "root";
        String password = "pepe";
        String query = sql;//"SELECT * FROM " + tab;

        ResultSetTableModel modelo = null;
        try {
            modelo = new ResultSetTableModel(driver, url, user, password, query);
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println("no conecto");
            e.printStackTrace();
        }
        tab.setModel(modelo);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * generated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        addPaciente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editPac = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tel3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajacalle = new javax.swing.JTextField();
        cajaNp = new javax.swing.JTextField();
        cajacol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tel2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        tel1 = new javax.swing.JTextField();
        habitbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deletePac = new javax.swing.JButton();
        cajanum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        cajaID = new javax.swing.JTextField();
        ap2p = new javax.swing.JTextField();
        ap1p = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        darAlta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_paciente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInternos = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cajaAp2Dv = new javax.swing.JTextField();
        cajaAp1D1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cajaID2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        consultorio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        nombreDoc = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addMedico = new javax.swing.JButton();
        deleteMedico = new javax.swing.JButton();
        updateMedico = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        crearCita = new javax.swing.JButton();
        ap12citas = new javax.swing.JTextField();
        citasNamePac = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        citasidDoc = new javax.swing.JTextField();
        guardarCita = new javax.swing.JButton();
        restablece = new javax.swing.JButton();
        eliminaCita = new javax.swing.JButton();
        cajaAp2D1 = new javax.swing.JTextField();
        cajaAp1D2 = new javax.swing.JTextField();
        citasNameDoc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cajaID3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fecha = new com.toedter.calendar.JDateChooser();
        cajaID4 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        ap11citas2 = new javax.swing.JTextField();
        ampm = new javax.swing.JComboBox<>();
        horas = new javax.swing.JComboBox<>();
        minutos = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 226, 247));
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Internos");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 220, -1));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Alta", "Internado", "Revision", "Citado" }));
        jPanel1.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, -1));

        addPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital.png"))); // NOI18N
        addPaciente.setText("Añade Paciente");
        addPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(addPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 60, 20));

        editPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        editPac.setText("Edita Paciente");
        editPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPacActionPerformed(evt);
            }
        });
        jPanel1.add(editPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 10, 20));

        tel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel3ActionPerformed(evt);
            }
        });
        jPanel1.add(tel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 10, 20));
        jPanel1.add(cajacalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, -1));

        cajaNp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNpActionPerformed(evt);
            }
        });
        cajaNp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaNpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaNpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNpKeyTyped(evt);
            }
        });
        jPanel1.add(cajaNp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, -1));
        jPanel1.add(cajacol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Habitacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));
        jPanel1.add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 40, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergencias", "Consultorios Seccion 1", "Laboratorios", "Sala de Partos", "Terapia Intensiva", "Consultorios Seccion 2", "Terapia Fisica" }));
        jComboBox3.setBorder(null);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 290, -1));

        tel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel1ActionPerformed(evt);
            }
        });
        jPanel1.add(tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 40, -1));
        jPanel1.add(habitbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 120, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Paciente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 20));

        deletePac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quitaMedico.png"))); // NOI18N
        deletePac.setText("Elimina Paciente");
        deletePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePacActionPerformed(evt);
            }
        });
        jPanel1.add(deletePac, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, 40));
        jPanel1.add(cajanum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 50, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Apellidos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Sala:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 60, 20));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        combo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo2ItemStateChanged(evt);
            }
        });
        jPanel1.add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 130, -1));

        cajaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaIDActionPerformed(evt);
            }
        });
        cajaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaIDKeyTyped(evt);
            }
        });
        jPanel1.add(cajaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 40, -1));

        ap2p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap2pKeyTyped(evt);
            }
        });
        jPanel1.add(ap2p, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, -1));

        ap1p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap1pKeyTyped(evt);
            }
        });
        jPanel1.add(ap1p, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefono");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 20));

        darAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alta.png"))); // NOI18N
        darAlta.setText("Dar de Alta");
        darAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darAltaActionPerformed(evt);
            }
        });
        jPanel1.add(darAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 160, 40));

        tabla_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idPaciente", "Nombre", "PrimAp", "SegAp", "Colonia", "Calle", "Num", "Telefono", "Estado", "Genero", "Sala"
            }
        ));
        tabla_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabla_pacienteMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_paciente);
        actualizarTabla("SELECT*FROM Paciente;",tabla_paciente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1150, 160));

        tablaInternos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "PrimAp", "SegAp", "Habitacion", "Sala", "NombreSala"
            }
        ));
        jScrollPane3.setViewportView(tablaInternos);
        actualizarTabla("SELECT*FROM internos;",tablaInternos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 160, 550, 140));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Pacientes");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, -1));

        jTabbedPane1.addTab("+Pacientes+", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaAp2Dv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaAp2DvKeyTyped(evt);
            }
        });
        jPanel2.add(cajaAp2Dv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

        cajaAp1D1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaAp1D1KeyTyped(evt);
            }
        });
        jPanel2.add(cajaAp1D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Genero:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 90, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Doctor:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 90, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        cajaID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaID2ActionPerformed(evt);
            }
        });
        jPanel2.add(cajaID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 40, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Apellidos:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 20));
        jPanel2.add(consultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 120, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Departamento:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 120, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Especializacion:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 160, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Consultorio:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 120, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Psicologia", "Nutricion", "Medicina General", "Cirugia", "Geriatria", "Ginecologia", "Pediatria" }));
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox6MouseReleased(evt);
            }
        });
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 160, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Medicos");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 220, -1));

        nombreDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDocActionPerformed(evt);
            }
        });
        nombreDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreDocKeyTyped(evt);
            }
        });
        jPanel2.add(nombreDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));

        jScrollPane4.setAutoscrolls(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdDoctor", "Nombre", "Ap1", "Ap2", "Especializacion", "Consultorio", "Departamento", "Genero", "Nombre Departamento"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);
        actualizarTabla("select*from docs_dept;",jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1020, 210));

        addMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor.png"))); // NOI18N
        addMedico.setText("Añadir Medico");
        addMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicoActionPerformed(evt);
            }
        });
        jPanel2.add(addMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 90, 160, -1));

        deleteMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quitaMedico.png"))); // NOI18N
        deleteMedico.setText("Eliminar Medico");
        deleteMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMedicoActionPerformed(evt);
            }
        });
        jPanel2.add(deleteMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 160, -1));

        updateMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        updateMedico.setText("Modificar Medico");
        updateMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMedicoActionPerformed(evt);
            }
        });
        jPanel2.add(updateMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 30));

        jTabbedPane1.addTab("+Doctores+", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/llamar.png"))); // NOI18N
        crearCita.setText("Crear Cita");
        crearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCitaActionPerformed(evt);
            }
        });
        jPanel3.add(crearCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 170, -1));

        ap12citas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap12citasKeyTyped(evt);
            }
        });
        jPanel3.add(ap12citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 110, -1));

        citasNamePac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                citasNamePacKeyTyped(evt);
            }
        });
        jPanel3.add(citasNamePac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Apellidos:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, 20));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Paciente");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 20));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nombre:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, 20));

        citasidDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasidDocActionPerformed(evt);
            }
        });
        jPanel3.add(citasidDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 40, -1));

        guardarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        guardarCita.setText("Guardar");
        guardarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCitaActionPerformed(evt);
            }
        });
        jPanel3.add(guardarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 170, -1));

        restablece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelCita.png"))); // NOI18N
        restablece.setText("Cancelar");
        restablece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restableceActionPerformed(evt);
            }
        });
        jPanel3.add(restablece, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 170, -1));

        eliminaCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N
        eliminaCita.setText("Eliminar");
        eliminaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaCitaActionPerformed(evt);
            }
        });
        jPanel3.add(eliminaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 170, -1));
        jPanel3.add(cajaAp2D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, -1));
        jPanel3.add(cajaAp1D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

        citasNameDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasNameDocActionPerformed(evt);
            }
        });
        jPanel3.add(citasNameDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("ID Doctor:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, 20));

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Doctor:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 60, 20));

        cajaID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaID3ActionPerformed(evt);
            }
        });
        jPanel3.add(cajaID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, 40, -1));

        jLabel28.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Apellidos:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Consultorio", "ID Dept", "Nombre Dept", "IdDocotor", "Doctor", "apeido Pat", "apeido Mat", "IdPaciente", "Paciente", "PrimAp", "SegAp"
            }
        ));
        actualizarTabla("Select*from citas_full;",jTable1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1150, 160));

        fecha.setDateFormatString("yyyy-MM-dd");
        fecha.setMaxSelectableDate(new java.util.Date(253370790065000L));
        fecha.setMinSelectableDate(new java.util.Date(-62135744335000L));
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 170, -1));

        cajaID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaID4ActionPerformed(evt);
            }
        });
        jPanel3.add(cajaID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 40, -1));

        jLabel32.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Fecha");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 20));

        jLabel33.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Hora");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, 20));

        ap11citas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap11citas2KeyTyped(evt);
            }
        });
        jPanel3.add(ap11citas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        ampm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PM", "AM" }));
        jPanel3.add(ampm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        horas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jPanel3.add(horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        minutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45", " " }));
        jPanel3.add(minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Doctor", "Doctor", "Apeido Paterno", "Apeido Materno"
            }
        ));
        actualizarTabla("Select IdDoctor, Nombre, Ap1 ,Ap2 from doctor;",jTable3);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable3MouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, 90));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Paciente", "Nombre", "Apeido", "Apeido Materno"
            }
        ));
        actualizarTabla("SELECT idPaciente, nombre, primAp, segAp from paciente;",jTable4);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable4MouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, 90));

        jTabbedPane1.addTab("+Citas+", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Reporte Citas");
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 170, -1));

        jButton10.setText("Reporte Doctores");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 170, -1));

        jButton11.setText("Reporte Pacientes");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 170, -1));

        jButton2.setText("Reporte Internos");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        DefaultPieDataset data2 = new DefaultPieDataset();
        ForGraphics fg=new ForGraphics();
        data2.setValue("Libre", fg.Cuenta(" select count(idHabitacion) from habitacion where Estado= 'Libre';"));
        data2.setValue("Ocupado", fg.Cuenta("select count(idHabitacion) from habitacion where Estado='Ocupada';"));

        JFreeChart chart2 = ChartFactory.createPieChart(
            "Ocupacion",
            data2, true, true, false);
        // Crear el Panel del Grafico con ChartPanel
        ChartPanel chartPanel2 = new ChartPanel(chart2);
        jPanel5.add(chartPanel2);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 500, 370));

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 500, 370));

        jTabbedPane1.addTab("+Estadistica+", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 710));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPacienteActionPerformed
try{
        String nomb, ap1, ap2, calle, col, tel,estado, gen;
int habit,pac, num;
PacienteDAO d = new PacienteDAO();
nomb=cajaNp.getText();ap1=ap1p.getText();ap2=ap2p.getText();calle=cajacalle.getText();col=cajacol.getText();
tel=tel1.getText()+"-"+tel2.getText()+"-"+tel3.getText(); estado=combo1.getSelectedItem().toString();gen=combo2.getSelectedItem().toString();
pac=Integer.parseInt(cajaID.getText()); habit=Integer.parseInt(habitbox.getText());num=Integer.parseInt(cajanum.getText());
if(d.buscaPaciente("idPaciente", String.valueOf(pac)).getIdPaciente()!=pac && d.buscaPaciente("nombre", cajaNp.getText()).getNombre()!=cajaNp.getText()){
  Paciente p = new Paciente(pac,nomb,ap1,ap2,col,calle,num,tel,estado,habit,gen);
  if(d.agregaPaciente(p)){
      JOptionPane.showMessageDialog(rootPane, "El registro se añadió correctamente", null, JOptionPane.INFORMATION_MESSAGE);
  }else{
      JOptionPane.showMessageDialog(rootPane, "El registro NO se añadio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
  }
  actualizarTabla("SELECT*FROM Paciente;",tabla_paciente);
  actualizarTabla("SELECT*FROM internos;",tablaInternos);
 cajaNp.setText("");ap1p.setText("");ap2p.setText("");cajacalle.setText("");cajacol.setText("");
 tel1.setText(""); tel2.setText("");tel3.setText("");combo1.setSelectedIndex(0);combo2.setSelectedIndex(0);
 cajaID.setText("");habitbox.setText("");cajanum.setText("");
}else{
     JOptionPane.showMessageDialog(rootPane, "Ya existe un registro con esos datos", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
}catch (NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
}  

        // TODO add your handling code here:
    }//GEN-LAST:event_addPacienteActionPerformed

    private void cajaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaIDActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel1ActionPerformed

    private void cajaID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaID2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void crearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCitaActionPerformed
        // TODO add your handling code here:
        try{
        String  h, fech;
int doc,pac;
CitasDAO c = new CitasDAO();
PacienteDAO p=new PacienteDAO();
h=horas.getSelectedItem().toString()+":"+minutos.getSelectedItem().toString()+":"+ampm.getSelectedItem();
pac=Integer.parseInt(cajaID4.getText());
doc=Integer.parseInt(citasidDoc.getText());
  SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
fech=  format.format(fecha.getDate()).toString();
System.out.println(fech);
if(c.buscaCita("paciente", String.valueOf(pac)).getPaciente()!=pac){
  Citas ci = new Citas(pac,doc,fech,h);
  if(c.generaCita(ci)){
      p.CitaPaciente(pac);
      JOptionPane.showMessageDialog(rootPane, "El registro se añadió correctamente", null, JOptionPane.INFORMATION_MESSAGE);
  }else{
      JOptionPane.showMessageDialog(rootPane, "El registro NO se añadio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
  }
  actualizarTabla("SELECT*FROM citas_full;",jTable1);
  actualizarTabla("SELECT*FROM paciente;",tabla_paciente);

cajaID4.setText("");
minutos.setSelectedIndex(0);
horas.setSelectedIndex(0);
ampm.setSelectedIndex(0);
citasidDoc.setText("");
}else{
     JOptionPane.showMessageDialog(rootPane, "Ya existe una cita con esos datos", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
        }catch(NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
        }  
        
    }//GEN-LAST:event_crearCitaActionPerformed

    private void citasidDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasidDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citasidDocActionPerformed

    private void citasNameDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasNameDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citasNameDocActionPerformed

    private void cajaID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaID3ActionPerformed
        // TODO add your handling code here:
        actualizarTabla("Select*From Paciente where idPaciente= "+cajaID.getText(),tabla_paciente);
    }//GEN-LAST:event_cajaID3ActionPerformed

    private void deleteMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMedicoActionPerformed
        // TODO add your handling code here:
            PacienteDAO p = new PacienteDAO();
         CitasDAO c=new CitasDAO();
        try{
            int pac= Integer.parseInt(cajaID2.getText());
            if(c.Elimina("IdDoctor", String.valueOf(pac), "Doctor")){
                p.QuitaCita(pac);
                            JOptionPane.showMessageDialog(rootPane, "Se elimino el registro", null, JOptionPane.INFORMATION_MESSAGE);
                             actualizarTabla("SELECT*FROM docs_dept;",jTable2);
                             
            }else
                            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el registro", null, JOptionPane.INFORMATION_MESSAGE);
  
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Revisa el Campo ID Doctor", null, JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_deleteMedicoActionPerformed

    private void cajaID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaID4ActionPerformed

    private void editPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPacActionPerformed
        // TODO add your handling code here:
        String nomb, ap1, ap2, calle, col, tel,estado, gen;
int habit,pac, num;
PacienteDAO d = new PacienteDAO();
try{
nomb=cajaNp.getText();ap1=ap1p.getText();ap2=ap2p.getText();calle=cajacalle.getText();col=cajacol.getText();
tel=tel1.getText()+"-"+tel2.getText()+"-"+tel3.getText(); estado=combo1.getSelectedItem().toString();gen=combo2.getSelectedItem().toString();
pac=Integer.parseInt(cajaID.getText()); habit=Integer.parseInt(habitbox.getText());num=Integer.parseInt(cajanum.getText());
if(d.buscaPaciente("idPaciente", String.valueOf(pac)).getIdPaciente()==pac){
  Paciente p = new Paciente(pac,nomb,ap1,ap2,col,calle,num,tel,estado,habit,gen);
  if(d.ModificaPaciente(p)){
      JOptionPane.showMessageDialog(rootPane, "El registro se modifico correctamente", null, JOptionPane.INFORMATION_MESSAGE);
  }else{
      JOptionPane.showMessageDialog(rootPane, "El registro NO se Modico", "ERROR", JOptionPane.INFORMATION_MESSAGE);
  }
  actualizarTabla("SELECT*FROM Paciente;",tabla_paciente);
  actualizarTabla("SELECT*FROM internos;",tablaInternos);
 cajaNp.setText("");ap1p.setText("");ap2p.setText("");cajacalle.setText("");cajacol.setText("");
 tel1.setText(""); tel2.setText("");tel3.setText("");combo1.setSelectedIndex(0);combo2.setSelectedIndex(0);
 cajaID.setText("");habitbox.setText("");cajanum.setText("");
}else{
     JOptionPane.showMessageDialog(rootPane, "El paciente no existe", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
}catch (NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
}  
    }//GEN-LAST:event_editPacActionPerformed

    private void tabla_pacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_pacienteMouseReleased
        // TODO add your handling code here:
        int t= tabla_paciente.getSelectedRow();
        cajaID.setText(tabla_paciente.getModel().getValueAt(t,0).toString());
        cajaNp.setText(tabla_paciente.getModel().getValueAt(t, 1).toString());
        ap1p.setText(tabla_paciente.getModel().getValueAt(t, 2).toString());
        ap2p.setText(tabla_paciente.getModel().getValueAt(t, 3).toString());
        cajacalle.setText(tabla_paciente.getModel().getValueAt(t, 4).toString());
        cajacol.setText(tabla_paciente.getModel().getValueAt(t, 5).toString());
        cajanum.setText(tabla_paciente.getModel().getValueAt(t,6).toString());
        tel1.setText(tabla_paciente.getModel().getValueAt(t, 7).toString().substring(0, 3));
        tel2.setText(tabla_paciente.getModel().getValueAt(t, 7).toString().substring(4, 7));
        tel3.setText(tabla_paciente.getModel().getValueAt(t, 7).toString().substring(8, 12));
        String s=tabla_paciente.getModel().getValueAt(t, 8).toString();
        combo1.setSelectedItem(s);
        habitbox.setText(tabla_paciente.getModel().getValueAt(t,9).toString());
        String s2=tabla_paciente.getModel().getValueAt(t, 10).toString();
        combo2.setSelectedItem(s2);
       
    }//GEN-LAST:event_tabla_pacienteMouseReleased

    private void deletePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePacActionPerformed
        // TODO add your handling code here:
        PacienteDAO p = new PacienteDAO();
        try{
            String pac= cajaID.getText();
            if(p.Elimina("idPaciente", pac, "paciente")){
                            JOptionPane.showMessageDialog(rootPane, "Se elimino el registro", null, JOptionPane.INFORMATION_MESSAGE);
                             actualizarTabla("SELECT*FROM Paciente;",tabla_paciente);
                             actualizarTabla("SELECT*FROM internos;",tablaInternos);
            }else
                            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el registro", null, JOptionPane.INFORMATION_MESSAGE);
  
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Revisa el Campo ID Paciente", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deletePacActionPerformed

    private void cajaNpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNpActionPerformed
        // TODO add your handling code here:
         actualizarTabla("Select*From Paciente where Nombre like '%"+cajaNp.getText()+"%';",tabla_paciente);
    }//GEN-LAST:event_cajaNpActionPerformed

    private void cajaNpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNpKeyReleased
  
    }//GEN-LAST:event_cajaNpKeyReleased

    private void cajaNpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNpKeyTyped
        // TODO add your handling code here:
          actualizarTabla("Select*From Paciente where Nombre like '%"+cajaNp.getText()+"%'",tabla_paciente);
          actualizarTabla("Select*From internos where Nombre like '%"+cajaNp.getText()+"%'",tablaInternos);
    }//GEN-LAST:event_cajaNpKeyTyped

    private void cajaNpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNpKeyPressed

    }//GEN-LAST:event_cajaNpKeyPressed

    private void cajaIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaIDKeyTyped
        // TODO add your handling code here:
        actualizarTabla("Select*From Paciente where idPaciente like '%"+cajaID.getText()+"%'",tabla_paciente);
    }//GEN-LAST:event_cajaIDKeyTyped

    private void ap1pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap1pKeyTyped
        // TODO add your handling code here:
        actualizarTabla("Select*From Paciente where PrimAp like '%"+ap1p.getText()+"%'",tabla_paciente);
        actualizarTabla("Select*From internos where PrimAp like '%"+ap1p.getText()+"%'",tablaInternos);
    }//GEN-LAST:event_ap1pKeyTyped

    private void ap2pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap2pKeyTyped
        // TODO add your handling code here:
        actualizarTabla("Select*From Paciente where SegAp like '%"+ap2p.getText()+"%'",tabla_paciente);
        actualizarTabla("Select*From internos where Nombre like '%"+ap2p.getText()+"%'",tablaInternos);
    }//GEN-LAST:event_ap2pKeyTyped

    private void darAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darAltaActionPerformed
        // TODO add your handling code here:
         String nomb, ap1, ap2, calle, col, tel,estado, gen;
int habit,pac, num;
PacienteDAO d = new PacienteDAO();
HabitacionDAO hab= new HabitacionDAO();
try{
nomb=cajaNp.getText();ap1=ap1p.getText();ap2=ap2p.getText();calle=cajacalle.getText();col=cajacol.getText();
tel=tel1.getText()+"-"+tel2.getText()+"-"+tel3.getText(); estado="De Alta";gen=combo2.getSelectedItem().toString();
pac=Integer.parseInt(cajaID.getText()); habit=Integer.parseInt(habitbox.getText());num=Integer.parseInt(cajanum.getText());
if(d.buscaPaciente("idPaciente", String.valueOf(pac)).getIdPaciente()==pac){
  Paciente p = new Paciente(pac,nomb,ap1,ap2,col,calle,num,tel,estado,habit,gen);
  if(d.DarAlta(pac)){
      hab.liberaHabitacion(habit);
      JOptionPane.showMessageDialog(rootPane, "Se dio de Alta al paciente", null, JOptionPane.INFORMATION_MESSAGE);
  }else{
      JOptionPane.showMessageDialog(rootPane, "El registro NO se Modico", "ERROR", JOptionPane.INFORMATION_MESSAGE);
  }
  actualizarTabla("SELECT*FROM Paciente;",tabla_paciente);
  actualizarTabla("SELECT*FROM internos;",tablaInternos);
 cajaNp.setText("");ap1p.setText("");ap2p.setText("");cajacalle.setText("");cajacol.setText("");
 tel1.setText(""); tel2.setText("");tel3.setText("");combo1.setSelectedIndex(0);combo2.setSelectedIndex(0);
 cajaID.setText("");habitbox.setText("");cajanum.setText("");
}else{
     JOptionPane.showMessageDialog(rootPane, "El paciente no existe", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
}catch (NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
}  
    }//GEN-LAST:event_darAltaActionPerformed

    private void combo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo2ItemStateChanged
        // TODO add your handling code here:
        if("De Alta".equals(combo1.getSelectedItem().toString())){
             actualizarTabla("SELECT*FROM Paciente where estado = 'De Alta';",tabla_paciente);
        }else if ("Citado".equals(combo1.getSelectedItem().toString())){
            actualizarTabla("SELECT*FROM Paciente where estado = 'Citado';",tabla_paciente);
        }else if("Revision".equals(combo1.getSelectedItem().toString())){
            actualizarTabla("SELECT*FROM Paciente where estado = 'Revision';",tabla_paciente);
        }else if("Internado".equals(combo1.getSelectedItem().toString())){
            actualizarTabla("SELECT*FROM Paciente where estado = 'Internado';",tabla_paciente);
        }
    }//GEN-LAST:event_combo2ItemStateChanged

    private void jComboBox6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MouseReleased

    private void citasNamePacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citasNamePacKeyTyped
        // TODO add your handling code here:
         actualizarTabla("Select*From citas_full where paciente like '%"+citasNamePac.getText()+"%'",jTable1);
    }//GEN-LAST:event_citasNamePacKeyTyped

    private void ap12citasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap12citasKeyTyped
        // TODO add your handling code here:
         actualizarTabla("Select*From Paciente where SegAp like '%"+ap12citas.getText()+"%'",jTable1);
    }//GEN-LAST:event_ap12citasKeyTyped

    private void restableceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restableceActionPerformed
        // TODO add your handling code here:
        //java.util.Date x=fecha.getDate();
        
        //DateFormat f=new SimpleDateFormat("dd-MM-yyyy");
        //String fecha2=f.format(fecha);
        cajaID4.setText("");
minutos.setSelectedIndex(0);
horas.setSelectedIndex(0);
ampm.setSelectedIndex(0);
citasidDoc.setText("");
    }//GEN-LAST:event_restableceActionPerformed

    private void ap11citas2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap11citas2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ap11citas2KeyTyped

    private void guardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCitaActionPerformed
        // TODO add your handling code here:
          try{
        String  h, fech;
int doc,pac;
CitasDAO c = new CitasDAO();
PacienteDAO p=new PacienteDAO();
h=horas.getSelectedItem().toString()+":"+minutos.getSelectedItem().toString()+":"+ampm.getSelectedItem();
pac=Integer.parseInt(cajaID4.getText());
doc=Integer.parseInt(citasidDoc.getText());
  SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
fech=  format.format(fecha.getDate()).toString();
System.out.println(fech);
if((c.buscaCita("paciente", String.valueOf(pac)).getPaciente()==pac && c.buscaCita("doctor", String.valueOf(doc)).getDoctor()==doc)){
  Citas ci = new Citas(pac,doc,fech,h);
  if(c.ModificaCita(ci)){
      p.CitaPaciente(pac);
      JOptionPane.showMessageDialog(rootPane, "El registro se Modifico correctamente", null, JOptionPane.INFORMATION_MESSAGE);
  }else{
      JOptionPane.showMessageDialog(rootPane, "El registro NO se modifico", "ERROR", JOptionPane.INFORMATION_MESSAGE);
  }
  actualizarTabla("SELECT*FROM citas_full;",jTable1);
  actualizarTabla("SELECT*FROM paciente;",tabla_paciente);

cajaID4.setText("");
minutos.setSelectedIndex(0);
horas.setSelectedIndex(0);
ampm.setSelectedIndex(0);
citasidDoc.setText("");
}else{
     JOptionPane.showMessageDialog(rootPane, "Ya existe una cita con esos datos", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
        }catch(NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
        }  
    }//GEN-LAST:event_guardarCitaActionPerformed

    private void eliminaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaCitaActionPerformed
        // TODO add your handling code here:
         PacienteDAO p = new PacienteDAO();
         CitasDAO c=new CitasDAO();
        try{
            int pac= Integer.parseInt(cajaID4.getText());
            if(c.Elimina("paciente", String.valueOf(pac), "cita")){
                p.QuitaCita(pac);
                            JOptionPane.showMessageDialog(rootPane, "Se elimino el registro", null, JOptionPane.INFORMATION_MESSAGE);
                             actualizarTabla("SELECT*FROM citas_full;",jTable1);
                             
            }else
                            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el registro", null, JOptionPane.INFORMATION_MESSAGE);
  
        }catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(rootPane, "Revisa el Campo ID Paciente", null, JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_eliminaCitaActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int t= jTable1.getSelectedRow();
        citasNamePac.setText(jTable1.getModel().getValueAt(t, 10).toString());
        //fecha.setDate(Date.valueOf(jTable1.getModel().getValueAt(t, 0).toString()));
        cajaID4.setText(jTable1.getModel().getValueAt(t, 9).toString());
        ap11citas2.setText(jTable1.getModel().getValueAt(t, 11).toString());
        ap12citas.setText(jTable1.getModel().getValueAt(t, 12).toString());
        horas.setSelectedItem(jTable1.getModel().getValueAt(t, 1).toString().substring(0,2));
        minutos.setSelectedItem(jTable1.getModel().getValueAt(t, 1).toString().substring(4,5));
        ampm.setSelectedItem(jTable1.getModel().getValueAt(t, 1).toString().substring(7,8));
        citasNameDoc.setText(jTable1.getModel().getValueAt(t, 6).toString());
        citasidDoc.setText(jTable1.getModel().getValueAt(t, 5).toString());
        cajaAp1D2.setText(jTable1.getModel().getValueAt(t, 7).toString());
        cajaAp2D1.setText(jTable1.getModel().getValueAt(t, 8).toString());
        
        
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseReleased
        // TODO add your handling code here:
        int t= jTable4.getSelectedRow();
        citasNamePac.setText(jTable4.getModel().getValueAt(t, 1).toString());
        cajaID4.setText(jTable4.getModel().getValueAt(t, 0).toString());
        ap11citas2.setText(jTable4.getModel().getValueAt(t, 2).toString());
        ap12citas.setText(jTable4.getModel().getValueAt(t, 3).toString());
        
    }//GEN-LAST:event_jTable4MouseReleased

    private void jTable3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseReleased
        // TODO add your handling code here:
        int t= jTable3.getSelectedRow();
        citasNameDoc.setText(jTable3.getModel().getValueAt(t, 1).toString());
        citasidDoc.setText(jTable3.getModel().getValueAt(t, 0).toString());
        cajaAp1D2.setText(jTable3.getModel().getValueAt(t, 2).toString());
        cajaAp2D1.setText(jTable3.getModel().getValueAt(t, 3).toString());
    }//GEN-LAST:event_jTable3MouseReleased

    private void tel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel3ActionPerformed

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
        int t= jTable2.getSelectedRow();
        cajaID2.setText(jTable2.getModel().getValueAt(t,0).toString());
        nombreDoc.setText(jTable2.getModel().getValueAt(t,1).toString());
        cajaAp1D1.setText(jTable2.getModel().getValueAt(t,2).toString());
        cajaAp2Dv.setText(jTable2.getModel().getValueAt(t,3).toString());
        jTextField1.setText(jTable2.getModel().getValueAt(t,4).toString());
        consultorio.setText(jTable2.getModel().getValueAt(t,5).toString());
        jComboBox6.setSelectedItem(jTable2.getModel().getValueAt(t,8).toString());
         jComboBox5.setSelectedItem(jTable2.getModel().getValueAt(t,7).toString());
        
    }//GEN-LAST:event_jTable2MouseReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nombreDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDocActionPerformed

    private void nombreDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreDocKeyTyped
        // TODO add your handling code here:
         actualizarTabla("Select*From docs_dept where Nombre like '%"+nombreDoc.getText()+"%'",jTable2);
    }//GEN-LAST:event_nombreDocKeyTyped

    private void cajaAp1D1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaAp1D1KeyTyped
        // TODO add your handling code here:
         actualizarTabla("Select*From docs_dept where Ap1 like '%"+cajaAp2D1.getText()+"%'",jTable2);
    }//GEN-LAST:event_cajaAp1D1KeyTyped

    private void cajaAp2DvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaAp2DvKeyTyped
        // TODO add your handling code here:
         actualizarTabla("Select*From docs_dept where Ap2 like '%"+cajaAp2Dv.getText()+"%'",jTable2);
    }//GEN-LAST:event_cajaAp2DvKeyTyped

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        // TODO add your handling code here:;
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void addMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicoActionPerformed
        // TODO add your handling code here:
        try{
         int id = Integer.parseInt(cajaID2.getText());
        String name=nombreDoc.getText();
        String  ap= cajaAp1D1.getText();
        String ap2 = cajaAp2Dv.getText();
       String esp = jTextField1.getText();
        int con = Integer.parseInt(consultorio.getText());
        int dep = jComboBox6.getSelectedIndex()+1;
         String gen = jComboBox5.getSelectedItem().toString();
            DoctorDAO d = new DoctorDAO();
            if(d.buscaDoctor("IdDoctor", String.valueOf(id)) == null && d.buscaDoctor("nombre", name)==null){
                Doctor p = new Doctor(id,name,ap,ap2,esp,con,dep,gen);
                if(d.agregaDoctor(p)){
                    JOptionPane.showMessageDialog(rootPane, "El registro se añadió correctamente", null, JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "El registro NO se añadio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                 }
  actualizarTabla("SELECT*FROM docs_dept;",jTable2);
   nombreDoc.setText("");
        cajaAp1D1.setText("");
       cajaAp2Dv.setText("");
       jTextField1.setText("");
       consultorio.setText("");
        jComboBox6.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);

}else{
     JOptionPane.showMessageDialog(rootPane, "Ya existe un registro con esos datos", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
}catch (NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
}  
         
        
    }//GEN-LAST:event_addMedicoActionPerformed

    private void updateMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMedicoActionPerformed
        // TODO add your handling code here:
               try{
         int id = Integer.parseInt(cajaID2.getText());
        String name=nombreDoc.getText();
        String  ap= cajaAp1D1.getText();
        String ap2 = cajaAp2Dv.getText();
       String esp = jTextField1.getText();
        int con = Integer.parseInt(consultorio.getText());
        int dep = jComboBox6.getSelectedIndex();
        dep=dep+1;
         String gen = jComboBox5.getSelectedItem().toString();
            DoctorDAO d = new DoctorDAO();
            if(d.buscaDoctor("IdDoctor", String.valueOf(id)) == null && d.buscaDoctor("nombre", name)==null){
                Doctor p = new Doctor(id,name,ap,ap2,esp,con,dep,gen);
                if(d.ModificaDoctor(p)){
                    JOptionPane.showMessageDialog(rootPane, "El registro se añadió correctamente", null, JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "El registro NO se añadio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                 }
  actualizarTabla("SELECT*FROM docs_dept;",jTable2);
   nombreDoc.setText("");
        cajaAp1D1.setText("");
       cajaAp2Dv.setText("");
       jTextField1.setText("");
       consultorio.setText("");
        jComboBox6.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);

}else{
     JOptionPane.showMessageDialog(rootPane, "Ya existe un registro con esos datos", "INFO", JOptionPane.INFORMATION_MESSAGE);
}
}catch (NumberFormatException e2){
    JOptionPane.showMessageDialog(rootPane, " Revisa Los Campos", null, JOptionPane.INFORMATION_MESSAGE);
}  
         
    }//GEN-LAST:event_updateMedicoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedico;
    private javax.swing.JButton addPaciente;
    private javax.swing.JComboBox<String> ampm;
    private javax.swing.JTextField ap11citas2;
    private javax.swing.JTextField ap12citas;
    private javax.swing.JTextField ap1p;
    private javax.swing.JTextField ap2p;
    private javax.swing.JTextField cajaAp1D1;
    private javax.swing.JTextField cajaAp1D2;
    private javax.swing.JTextField cajaAp2D1;
    private javax.swing.JTextField cajaAp2Dv;
    private javax.swing.JTextField cajaID;
    private javax.swing.JTextField cajaID2;
    private javax.swing.JTextField cajaID3;
    private javax.swing.JTextField cajaID4;
    private javax.swing.JTextField cajaNp;
    private javax.swing.JTextField cajacalle;
    private javax.swing.JTextField cajacol;
    private javax.swing.JTextField cajanum;
    private javax.swing.JTextField citasNameDoc;
    private javax.swing.JTextField citasNamePac;
    private javax.swing.JTextField citasidDoc;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JTextField consultorio;
    private javax.swing.JButton crearCita;
    private javax.swing.JButton darAlta;
    private javax.swing.JButton deleteMedico;
    private javax.swing.JButton deletePac;
    private javax.swing.JButton editPac;
    private javax.swing.JButton eliminaCita;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardarCita;
    private javax.swing.JTextField habitbox;
    private javax.swing.JComboBox<String> horas;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> minutos;
    private javax.swing.JTextField nombreDoc;
    private javax.swing.JButton restablece;
    private javax.swing.JTable tablaInternos;
    private javax.swing.JTable tabla_paciente;
    private javax.swing.JTextField tel1;
    private javax.swing.JTextField tel2;
    private javax.swing.JTextField tel3;
    private javax.swing.JButton updateMedico;
    // End of variables declaration//GEN-END:variables
}
